name: deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write    # ✅ required for OIDC authentication
  contents: read     # ✅ required to checkout the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Azure login with OIDC
      - name: Azure login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Log in to ACR
      - name: ACR docker login
        run: |
          az acr login --name ${{ secrets.AZURE_ACR_NAME }}

      # Build & tag Docker image
      - name: Build and tag image
        run: |
          IMAGE=${{ secrets.AZURE_ACR_NAME }}.azurecr.io/prod-frontend:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE ./frontend

      # Push image to ACR
      - name: Push image to ACR
        run: |
          docker push $IMAGE

      # Deploy to Azure Container Apps (Production)
      - name: Deploy to Azure Container Apps (Production)
        run: |
          az containerapp update \
            --name aca-frontend-prod \
            --resource-group RG_SIT722_PROD \
            --image $IMAGE