name: CD Production

on:
  push:
    branches:
      - main

env:
  REGISTRY: aakankshaacr722.azurecr.io
  IMAGE_NAME: sit722-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and tag image
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GIT_SHA} .
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GIT_SHA} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:prod-latest

      - name: Push image to ACR
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GIT_SHA}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:prod-latest

      - name: Deploy to Azure Container Apps (Production)
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          az containerapp update \
            -n sit722-prod \
            -g RG_SIT722_PROD \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GIT_SHA}