name: Deploy to Azure Container Apps (Production)

on:
  push:
    branches:
      - main   # only trigger on main branch pushes

env:
  RESOURCE_GROUP: RG_SIT722_PROD
  ACA_ENV: aca-env-prod
  APP_NAME: aca-frontend-prod
  ACR_NAME: aakankshaacr722

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC login
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Azure login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR docker login
        run: az acr login --name $ACR_NAME

      - name: Build & Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $ACR_NAME.azurecr.io/frontend:latest \
            -t $ACR_NAME.azurecr.io/frontend:${{ github.sha }} \
            ./frontend \
            --push

      - name: Deploy to Azure Container Apps (Production)
        run: |
          az containerapp update \
            -g $RESOURCE_GROUP \
            -n $APP_NAME \
            --image $ACR_NAME.azurecr.io/frontend:${{ github.sha }}